export const fieldData = [{
  "data": {
    "field": {
      "tournamentName": "The Sentry",
      "id": "R2024016",
      "lastUpdated": 1704141922473,
      "message": null,
      "features": [],
      "players": [
        {
          "id": "52955",
          "alphaSort": "Å",
          "firstName": "Ludvig",
          "lastName": "Åberg",
          "shortName": "L. Åberg",
          "displayName": "Åberg, Ludvig",
          "amateur": false,
          "favorite": false,
          "country": "Sweden",
          "countryFlag": "SWE",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_52955.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "33948",
          "alphaSort": "A",
          "firstName": "Byeong Hun",
          "lastName": "An",
          "shortName": "B. An",
          "displayName": "An, Byeong Hun",
          "amateur": false,
          "favorite": false,
          "country": "South Korea",
          "countryFlag": "KOR",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_33948.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "56630",
          "alphaSort": "B",
          "firstName": "Akshay",
          "lastName": "Bhatia",
          "shortName": "A. Bhatia",
          "displayName": "Bhatia, Akshay",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_56630.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "33141",
          "alphaSort": "B",
          "firstName": "Keegan",
          "lastName": "Bradley",
          "shortName": "K. Bradley",
          "displayName": "Bradley, Keegan",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_33141.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47504",
          "alphaSort": "B",
          "firstName": "Sam",
          "lastName": "Burns",
          "shortName": "S. Burns",
          "displayName": "Burns, Sam",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47504.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "35450",
          "alphaSort": "C",
          "firstName": "Patrick",
          "lastName": "Cantlay",
          "shortName": "P. Cantlay",
          "displayName": "Cantlay, Patrick",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_35450.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "51766",
          "alphaSort": "C",
          "firstName": "Wyndham",
          "lastName": "Clark",
          "shortName": "W. Clark",
          "displayName": "Clark, Wyndham",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_51766.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47591",
          "alphaSort": "C",
          "firstName": "Eric",
          "lastName": "Cole",
          "shortName": "E. Cole",
          "displayName": "Cole, Eric",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47591.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "39997",
          "alphaSort": "C",
          "firstName": "Corey",
          "lastName": "Conners",
          "shortName": "C. Conners",
          "displayName": "Conners, Corey",
          "amateur": false,
          "favorite": false,
          "country": "Canada",
          "countryFlag": "CAN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_39997.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "45157",
          "alphaSort": "D",
          "firstName": "Cam",
          "lastName": "Davis",
          "shortName": "C. Davis",
          "displayName": "Davis, Cam",
          "amateur": false,
          "favorite": false,
          "country": "Australia",
          "countryFlag": "AUS",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_45157.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "28089",
          "alphaSort": "D",
          "firstName": "Jason",
          "lastName": "Day",
          "shortName": "J. Day",
          "displayName": "Day, Jason",
          "amateur": false,
          "favorite": false,
          "country": "Australia",
          "countryFlag": "AUS",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_28089.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "51349",
          "alphaSort": "E",
          "firstName": "Nico",
          "lastName": "Echavarria",
          "shortName": "N. Echavarria",
          "displayName": "Echavarria, Nico",
          "amateur": false,
          "favorite": false,
          "country": "Colombia",
          "countryFlag": "COL",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_51349.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "34099",
          "alphaSort": "E",
          "firstName": "Harris",
          "lastName": "English",
          "shortName": "H. English",
          "displayName": "English, Harris",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_34099.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "29725",
          "alphaSort": "F",
          "firstName": "Tony",
          "lastName": "Finau",
          "shortName": "T. Finau",
          "displayName": "Finau, Tony",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_29725.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "40098",
          "alphaSort": "F",
          "firstName": "Matt",
          "lastName": "Fitzpatrick",
          "shortName": "M. Fitzpatrick",
          "displayName": "Fitzpatrick, Matt",
          "amateur": false,
          "favorite": false,
          "country": "England",
          "countryFlag": "ENG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_40098.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "30911",
          "alphaSort": "F",
          "firstName": "Tommy",
          "lastName": "Fleetwood",
          "shortName": "T. Fleetwood",
          "displayName": "Fleetwood, Tommy",
          "amateur": false,
          "favorite": false,
          "country": "England",
          "countryFlag": "ENG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_30911.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "32102",
          "alphaSort": "F",
          "firstName": "Rickie",
          "lastName": "Fowler",
          "shortName": "R. Fowler",
          "displayName": "Fowler, Rickie",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_32102.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "25900",
          "alphaSort": "G",
          "firstName": "Lucas",
          "lastName": "Glover",
          "shortName": "L. Glover",
          "displayName": "Glover, Lucas",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_25900.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "31646",
          "alphaSort": "G",
          "firstName": "Emiliano",
          "lastName": "Grillo",
          "shortName": "E. Grillo",
          "displayName": "Grillo, Emiliano",
          "amateur": false,
          "favorite": false,
          "country": "Argentina",
          "countryFlag": "ARG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_31646.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "33399",
          "alphaSort": "H",
          "firstName": "Adam",
          "lastName": "Hadwin",
          "shortName": "A. Hadwin",
          "displayName": "Hadwin, Adam",
          "amateur": false,
          "favorite": false,
          "country": "Canada",
          "countryFlag": "CAN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_33399.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47988",
          "alphaSort": "H",
          "firstName": "Nick",
          "lastName": "Hardy",
          "shortName": "N. Hardy",
          "displayName": "Hardy, Nick",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47988.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "27644",
          "alphaSort": "H",
          "firstName": "Brian",
          "lastName": "Harman",
          "shortName": "B. Harman",
          "displayName": "Harman, Brian",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_27644.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "34363",
          "alphaSort": "H",
          "firstName": "Tyrrell",
          "lastName": "Hatton",
          "shortName": "T. Hatton",
          "displayName": "Hatton, Tyrrell",
          "amateur": false,
          "favorite": false,
          "country": "England",
          "countryFlag": "ENG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_34363.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "34098",
          "alphaSort": "H",
          "firstName": "Russell",
          "lastName": "Henley",
          "shortName": "R. Henley",
          "displayName": "Henley, Russell",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_34098.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "54628",
          "alphaSort": "H",
          "firstName": "Lee",
          "lastName": "Hodges",
          "shortName": "L. Hodges",
          "displayName": "Hodges, Lee",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_54628.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "35532",
          "alphaSort": "H",
          "firstName": "Tom",
          "lastName": "Hoge",
          "shortName": "T. Hoge",
          "displayName": "Hoge, Tom",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_35532.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "39977",
          "alphaSort": "H",
          "firstName": "Max",
          "lastName": "Homa",
          "shortName": "M. Homa",
          "displayName": "Homa, Max",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_39977.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "46717",
          "alphaSort": "H",
          "firstName": "Viktor",
          "lastName": "Hovland",
          "shortName": "V. Hovland",
          "displayName": "Hovland, Viktor",
          "amateur": false,
          "favorite": false,
          "country": "Norway",
          "countryFlag": "NOR",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_46717.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "35506",
          "alphaSort": "H",
          "firstName": "Mackenzie",
          "lastName": "Hughes",
          "shortName": "M. Hughes",
          "displayName": "Hughes, Mackenzie",
          "amateur": false,
          "favorite": false,
          "country": "Canada",
          "countryFlag": "CAN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_35506.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "39971",
          "alphaSort": "I",
          "firstName": "Sungjae",
          "lastName": "Im",
          "shortName": "S. Im",
          "displayName": "Im, Sungjae",
          "amateur": false,
          "favorite": false,
          "country": "South Korea",
          "countryFlag": "KOR",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_39971.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "37455",
          "alphaSort": "K",
          "firstName": "Si Woo",
          "lastName": "Kim",
          "shortName": "S.W.. Kim",
          "displayName": "Kim, Si Woo",
          "amateur": false,
          "favorite": false,
          "country": "South Korea",
          "countryFlag": "KOR",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_37455.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "55182",
          "alphaSort": "K",
          "firstName": "Tom",
          "lastName": "Kim",
          "shortName": "T. Kim",
          "displayName": "Kim, Tom",
          "amateur": false,
          "favorite": false,
          "country": "South Korea",
          "countryFlag": "KOR",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_55182.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "30926",
          "alphaSort": "K",
          "firstName": "Chris",
          "lastName": "Kirk",
          "shortName": "C. Kirk",
          "displayName": "Kirk, Chris",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_30926.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "48117",
          "alphaSort": "K",
          "firstName": "Kurt",
          "lastName": "Kitayama",
          "shortName": "K. Kitayama",
          "displayName": "Kitayama, Kurt",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_48117.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "27129",
          "alphaSort": "L",
          "firstName": "Luke",
          "lastName": "List",
          "shortName": "L. List",
          "displayName": "List, Luke",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_27129.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "32839",
          "alphaSort": "M",
          "firstName": "Hideki",
          "lastName": "Matsuyama",
          "shortName": "H. Matsuyama",
          "displayName": "Matsuyama, Hideki",
          "amateur": false,
          "favorite": false,
          "country": "Japan",
          "countryFlag": "JPN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_32839.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47993",
          "alphaSort": "M",
          "firstName": "Denny",
          "lastName": "McCarthy",
          "shortName": "D. McCarthy",
          "displayName": "McCarthy, Denny",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47993.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "49947",
          "alphaSort": "M",
          "firstName": "Taylor",
          "lastName": "Moore",
          "shortName": "T. Moore",
          "displayName": "Moore, Taylor",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_49947.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "50525",
          "alphaSort": "M",
          "firstName": "Collin",
          "lastName": "Morikawa",
          "shortName": "C. Morikawa",
          "displayName": "Morikawa, Collin",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_50525.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "51070",
          "alphaSort": "N",
          "firstName": "Vincent",
          "lastName": "Norrman",
          "shortName": "V. Norrman",
          "displayName": "Norrman, Vincent",
          "amateur": false,
          "favorite": false,
          "country": "Sweden",
          "countryFlag": "SWE",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_51070.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "49771",
          "alphaSort": "P",
          "firstName": "J.T.",
          "lastName": "Poston",
          "shortName": "J.T.. Poston",
          "displayName": "Poston, J.T.",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_49771.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "28252",
          "alphaSort": "P",
          "firstName": "Seamus",
          "lastName": "Power",
          "shortName": "S. Power",
          "displayName": "Power, Seamus",
          "amateur": false,
          "favorite": false,
          "country": "Ireland",
          "countryFlag": "IRL",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_28252.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "34256",
          "alphaSort": "P",
          "firstName": "Andrew",
          "lastName": "Putnam",
          "shortName": "A. Putnam",
          "displayName": "Putnam, Andrew",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_34256.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47995",
          "alphaSort": "R",
          "firstName": "Davis",
          "lastName": "Riley",
          "shortName": "D. Riley",
          "displayName": "Riley, Davis",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47995.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "36699",
          "alphaSort": "R",
          "firstName": "Patrick",
          "lastName": "Rodgers",
          "shortName": "P. Rodgers",
          "displayName": "Rodgers, Patrick",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_36699.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "22405",
          "alphaSort": "R",
          "firstName": "Justin",
          "lastName": "Rose",
          "shortName": "J. Rose",
          "displayName": "Rose, Justin",
          "amateur": false,
          "favorite": false,
          "country": "England",
          "countryFlag": "ENG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_22405.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "48081",
          "alphaSort": "S",
          "firstName": "Xander",
          "lastName": "Schauffele",
          "shortName": "X. Schauffele",
          "displayName": "Schauffele, Xander",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_48081.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "46046",
          "alphaSort": "S",
          "firstName": "Scottie",
          "lastName": "Scheffler",
          "shortName": "S. Scheffler",
          "displayName": "Scheffler, Scottie",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_46046.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "47347",
          "alphaSort": "S",
          "firstName": "Adam",
          "lastName": "Schenk",
          "shortName": "A. Schenk",
          "displayName": "Schenk, Adam",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_47347.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "34046",
          "alphaSort": "S",
          "firstName": "Jordan",
          "lastName": "Spieth",
          "shortName": "J. Spieth",
          "displayName": "Spieth, Jordan",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_34046.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "49960",
          "alphaSort": "S",
          "firstName": "Sepp",
          "lastName": "Straka",
          "shortName": "S. Straka",
          "displayName": "Straka, Sepp",
          "amateur": false,
          "favorite": false,
          "country": "Austria",
          "countryFlag": "AUT",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_49960.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "40115",
          "alphaSort": "S",
          "firstName": "Adam",
          "lastName": "Svensson",
          "shortName": "A. Svensson",
          "displayName": "Svensson, Adam",
          "amateur": false,
          "favorite": false,
          "country": "Canada",
          "countryFlag": "CAN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_40115.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "25493",
          "alphaSort": "T",
          "firstName": "Nick",
          "lastName": "Taylor",
          "shortName": "N. Taylor",
          "displayName": "Taylor, Nick",
          "amateur": false,
          "favorite": false,
          "country": "Canada",
          "countryFlag": "CAN",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_25493.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "51634",
          "alphaSort": "T",
          "firstName": "Sahith",
          "lastName": "Theegala",
          "shortName": "S. Theegala",
          "displayName": "Theegala, Sahith",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_51634.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "30927",
          "alphaSort": "T",
          "firstName": "Brendon",
          "lastName": "Todd",
          "shortName": "B. Todd",
          "displayName": "Todd, Brendon",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_30927.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "40006",
          "alphaSort": "v",
          "firstName": "Erik",
          "lastName": "van Rooyen",
          "shortName": "E. van Rooyen",
          "displayName": "van Rooyen, Erik",
          "amateur": false,
          "favorite": false,
          "country": "South Africa",
          "countryFlag": "RSA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_40006.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "27770",
          "alphaSort": "V",
          "firstName": "Camilo",
          "lastName": "Villegas",
          "shortName": "C. Villegas",
          "displayName": "Villegas, Camilo",
          "amateur": false,
          "favorite": false,
          "country": "Colombia",
          "countryFlag": "COL",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_27770.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "48887",
          "alphaSort": "W",
          "firstName": "Matt",
          "lastName": "Wallace",
          "shortName": "M. Wallace",
          "displayName": "Wallace, Matt",
          "amateur": false,
          "favorite": false,
          "country": "England",
          "countryFlag": "ENG",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_48887.png",
          "qualifier": "Current Tournament Winners",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        },
        {
          "id": "57366",
          "alphaSort": "Y",
          "firstName": "Cameron",
          "lastName": "Young",
          "shortName": "Cam. Young",
          "displayName": "Young, Cameron",
          "amateur": false,
          "favorite": false,
          "country": "United States",
          "countryFlag": "USA",
          "headshot": "https://pga-tour-res.cloudinary.com/image/upload/c_fill,f_auto,g_face:center,h_${HEIGHT},q_auto,t_headshots_leaderboard_l,w_${WIDTH}/headshots_57366.png",
          "qualifier": "Top 50 on Prior Year's FedExCup Points List",
          "alternate": false,
          "withdrawn": false,
          "status": "IN",
          "owgr": null,
          "rankingPoints": null,
          "rankLogoLight": null,
          "rankLogoDark": null,
          "teammate": null
        }
      ],
      "alternates": [],
      "standingsHeader": "RANK"
    }
  }
}]